# Generated by Django 5.1 on 2026-06-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ism')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='contacts/')),
                ('category', models.CharField(choices=[('friends', "Do'stlar"), ('family', 'Qarindoshlar'), ('work', 'Ish'), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Kategoriya')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kontakt',
                'verbose_name_plural': 'Kontaktlar',
                'db_table': 'contacts',
                'ordering': ['-created_at'],
            },
        ),
    ]
