# Generated by Django 5.1 on 2026-06-19 09:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name="To'lov miqdori")),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'db_table': 'payments',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt_type', models.CharField(choices=[('gave', 'Men berdim'), ('got', 'Men oldim')], max_length=10, verbose_name='Turi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Miqdor')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name="To'langan miqdor")),
                ('currency', models.CharField(choices=[('UZS', "So'm"), ('USD', 'Dollar'), ('RUB', 'Rubl')], default='UZS', max_length=3, verbose_name='Valyuta')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('partial', "Qisman to'langan"), ('paid', "To'liq to'langan")], default='active', max_length=10, verbose_name='Holat')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Qaytarish muddati')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='debts/', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='contacts.contact', verbose_name='Kontakt')),
            ],
            options={
                'verbose_name': 'Qarz',
                'verbose_name_plural': 'Qarzlar',
                'db_table': 'debts',
                'ordering': ['-created_at'],
            },
        ),
    ]
